apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flask-mysql-demo
  region: us-west-2
  version: "1.29"

vpc:
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-west-2a: { cidr: "10.0.1.0/24" }
      us-west-2b: { cidr: "10.0.2.0/24" }

nodeGroups:
  - name: ng-public
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        albIngress: true