apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c

metadata:
  name: flask-mysql-demo
  region: us-west-2
  version: "1.30"
  tags:
    karpenter.sh/discovery: flask-mysql-demo
    created-by: eks-workshop-v2
    env: flask-mysql-demo

iam:
  withOIDC: true

vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

addons:
  - name: vpc-cni
    version: latest
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true"}'
    resolveConflicts: overwrite
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true

managedNodeGroups:
  - name: default
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    instanceType: t3.medium
    privateNetworking: true
    releaseVersion: "1.30"
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      workshop-default: "yes"
